import 'package:anilist/core/config/fp.dart';
import 'package:anilist/core/core.dart';
import 'package:anilist/features/home/data/data.dart';
import 'package:anilist/features/home/domain/domain.dart';
import 'package:anilist/features/home/graphql/__generated__/get_anime_list.data.gql.dart';

class HomeRepositoryImpl extends HomeRepository {
  final AnimeListRemoteDataSource animeListRemoteDataSource;

  HomeRepositoryImpl({required this.animeListRemoteDataSource});

  /// [fetchListAnime] function get stream of data from [animeListRemoteDataSource] injector
  /// and data are converted to [mediaList] which are iterable [GGetAnimeListData_Page_media] class data types generated by ferry gen
  /// further [animeModels] is list converted from [mediaList] to defined [AnimeModel]
  /// and lastly [animeEntities] is list converted from [animeModels] to defined [AnimeEntity]
  @override
  Stream<Result<List<AnimeEntity>>> getAnimeList() {
    return animeListRemoteDataSource.fetchListAnime().map((result) {
      return result.map((data) {
        final mediaList =
            data?.Page?.media?.whereType<GGetAnimeListData_Page_media>() ?? [];

        final animeModels = mediaList
            .map(
              (media) => AnimeModel(
                id: media.id,
                title: media.title?.english ?? 'Unknown',
                episodes: media.episodes,
                description: media.description ?? 'Unknown',
                coverImage: media.coverImage?.large,
                status: media.status?.name,
              ),
            )
            .toList();

        final animeEntities = animeModels
            .map((model) => model.toEntity())
            .toList();

        return animeEntities;
      });
    });
  }
}
